### PR TITLE
Get capo, tuning, and key

### PR DESCRIPTION
**Pull request by hougrammer**
Thanks for writing this scraper! I think it would be nice to get the capo, tuning, and key from the tab meta data. I looked in the JSON response and noticed these are easily accessible.

### CODE REVIEW

**Comment by masterT** [comment]
Implement issue #32.

**Comment by masterT** [comment]
@hougrammer Your test are failing.

**Comment by hougrammer** [comment]
I think I'm failing the tests now because I've changed the JSON schema.

**Comment by masterT** [comment]
Indeed, you can change it!

**Comment by hougrammer** [comment]
Sorry for the delay.  I changed tabs.json to match the new format.  The json schema now matches but now the search is broken.  I think it is unrelated because ultimate guitar is now putting an advertisement before the search results come up (this happens even on a clean clone of the repo).  I'm not super experienced with how to get past this.

**Comment by hougrammer** [comment]
Yes sir.  `README.md` is now updated with an example that has capo, tuning, and key.

**Comment by masterT** [comment]
😄 Thank you!

**Pull request merged**
